rename 'runtime' interface name to 'store'
WebAssembly/wasi-runtime-config pull request #14
Opened 2024-09-11 06:28 UTC by Mossaka

It renames:

`runtime` -> `store`
`config-error` -> `error`

and

delete the hand-written `config.md` in preference of the generated `imports.md` doc.

2024-09-11 16:18 UTC, lukewagner commented
Thanks!  To your question: originally, there was a sketch to use value imports to import configuration values, with 1 value import per individual configuration value, allowing the names of required configuration values to be known declaratively, allowing various DX/security/perf improvements.  But that was a much bigger lift (for the tooling and runtime), so we instead prioritized adding a more-dynamic (runtime) configuration interface (which we'd need in any case, since sometimes you just don't know AOT what configuration you need), hence the name of the repo.  Whatever the history, renaming the repo to wasi-config to match `wasi:config` makes sense to me.  Eventually, I'd like to return to the declarative value-import approach, we could just add that to this same repo (alongside `wasi:config/store`).

2024-09-12 20:48 UTC, devigned requested changes
Just words, no code

2024-09-12 20:48 UTC, devigned commented on imports.md
>  <p>An error type that encapsulates the different errors that can occur fetching config</p>
```suggestion
<p>An error type that encapsulates the different errors that can occur fetching configuration values.</p>
```

2024-09-12 20:48 UTC, devigned commented on imports.md
>  <p>Gets a single opaque config value set at the given key if it exists</p>
```suggestion
<p>Gets a string configuration value if the key exists. If the key does not exist, the value returned will be None.</p>
```

2024-09-12 20:48 UTC, devigned commented on imports.md
>  <p>Gets a list of all set config data</p>
```suggestion
<p>Gets a list of each configuration key and value.</p>
```

2024-09-12 20:48 UTC, devigned commented on wit/store.wit
>      /// Gets a list of all set config data
```suggestion
    /// Gets a list of each configuration key and value.
```

2024-09-12 22:14 UTC, devigned approved these changes
Thank you for improving upon my suggestions. LGTM!

2024-09-13 18:29 UTC, Mossaka commented
Could you please take a look? @thomastaylor312

2024-09-23 22:43 UTC, thomastaylor312 approved these changes

2024-09-23 22:47 UTC, thomastaylor312 commented
And I am all good with a repo rename

2024-09-24 00:02 UTC, merged